# Generated by Django 2.0.5 on 2018-07-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('icon', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
