# Generated by Django 2.0.5 on 2018-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=128),
        ),
    ]
