# Generated by Django 2.0.5 on 2018-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180715_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
